# Generated by Django 4.2.7 on 2023-12-21 00:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=50)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('plato', models.CharField(max_length=255, unique=True)),
                ('url', models.SlugField(max_length=255, unique=True)),
                ('intro', ckeditor.fields.RichTextField()),
                ('preparacion', ckeditor.fields.RichTextField()),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('destacada', models.BooleanField(default=False)),
                ('imagen', models.ImageField(upload_to='receta/imagenes/')),
                ('visible', models.BooleanField(default=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.categoria')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=5000)),
                ('visible', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.perfil')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.receta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
